### ISSUE TITLE
Early Stages Integration 

### ISSUE THREAD

**Issue by TheOnlyAesir** [WouterB15/blockblock#3]
Full log of all Issues encountered with integration.

Issue No.1.:

Locking crafting_recipe of crafting_rock does not produce expected result. Locking Interaction is possible.
For that matter locking any crafting_recipe for Early Stages does not seem to work.

**Comment by WouterB15** [comment]
Are you referring to the recipe of the crafting stone itself, or using the crafting grid ontop of the stone itself?

**Comment by TheOnlyAesir** [comment]
The recipe of the crafting stone itself - Have not tried using it because I did not think it will work
